import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { NavBar } from "../components/NavBar";
import ThemeContextProvider from '../contexts/theme-context';
import { ClerkProvider } from "@clerk/nextjs";
import { ConvexClientProvider } from "../components/providers/ConvexClientProvider";
import NavigationHeader from "import/components/NavigationHeader";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="darkgray" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#1e1e1e] text-[#f5f5f5] overflow-y-scroll`}
      >
        <ClerkProvider>
          <ConvexClientProvider>
            <NavigationHeader />
            {children}
          </ConvexClientProvider>
        </ClerkProvider>
      </body>
    </html>
  );
}
