import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { NavBar } from "../components/NavBar";
import ThemeContextProvider from '../contexts/theme-context';
import { ClerkProvider } from "@clerk/nextjs";
import { ConvexClientProvider } from "../components/providers/ConvexClientProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <link href="https://cdn.jsdelivr.net/npm/daisyui@5" rel="stylesheet" type="text/css" />
        <link href="https://cdn.jsdelivr.net/npm/daisyui@5/themes.css" rel="stylesheet" type="text/css" />
        <script src="https://cdn.jsdelivr.net/npm/@tailwindcss/browser@4"></script>
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased overflow-scroll`}
      >
        <ThemeContextProvider>
          <ClerkProvider>
            <ConvexClientProvider>
              <NavBar />
              {children}
            </ConvexClientProvider>
          </ClerkProvider>
        </ThemeContextProvider>
      </body>
    </html>
  );
}
